version: 1.0.0.{build}
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
shallow_clone: true
build_script:
- cmd: >-
    dotnet.exe restore Dot.Net.Extensions/Dot.Net.Extensions.sln

    dotnet.exe build Dot.Net.Extensions/Dot.Net.Extensions.sln
test_script:
- cmd: dotnet.exe test Dot.Net.Extensions/Dot.Net.Extensions.sln